name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: eu-central-1
        role-to-assume: arn:aws:iam::630388463273:role/Github_s3_access_jovovic-bucket
        role-session-name: GitHub-To-AWS-AssumeRole-Session




name: Deploy Website to S3

on:
  push:
    branches:
      - milos_branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Deploy to S3

      run: |
        aws s3 sync ./public/ s3://jovovic-bucket --delete



