name: Deploy Website to S3 create bucket if not exists

on:
  push:
    branches:
      - novi_branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Check if bucket exists
        id: check_bucket
        run: |
          if aws s3 ls "s3://${{ secrets.AWS_BUCKET_NAME }}" 2>&1 | grep -q 'NoSuchBucket'
          then
            echo "::set-output name=exists::false"
          else
            echo "::set-output name=exists::true"
          fi

      - name: Create S3 Bucket
        if: steps.check_bucket.outputs.exists == 'false'
        run: |
          aws s3 mb s3://${{ secrets.AWS_BUCKET_NAME }}
          aws s3 website s3://${{ secrets.AWS_BUCKET_NAME }} --index-document index.html --error-document error.html
          aws s3api put-bucket-policy --bucket ${{ secrets.AWS_BUCKET_NAME }} --policy '{"Version":"2012-10-17","Statement":[{"Sid":"PublicReadForGetBucketObjects","Effect":"Allow","Principal": "*","Action":["s3:GetObject"],"Resource":["arn:aws:s3:::${{ secrets.AWS_BUCKET_NAME }}/*"]}]}'

      - name: Build and Deploy to S3
        if: steps.check_bucket.outputs.exists == 'true'
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_BUCKET_NAME }} --delete --acl public-read
