name: Deploy Website

on:
  push:
    branches:
      - novi_branch

env:
  AWS_REGION: eu-central-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Create S3 bucket
      run: |
        aws s3 mb s3://jovovic-novi-bucket --region ${{ env.AWS_REGION }}
        aws s3 website s3://jovovic-novi-bucket/ --index-document index.html --error-document error.html --region ${{ env.AWS_REGION }}
    
    - name: Sync to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: jovovic-novi-bucket
        AWS_REGION: ${{ env.AWS_REGION }}
        SOURCE_DIR: 'dist'
